nname: Monitor de Sismos Colombia

on:
  schedule:
    # Se ejecuta automáticamente cada 5 minutos
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permite probarlo manualmente cuando quieras

jobs:
  check-earthquakes:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: |
          pip install requests

      - name: Ejecutar script de rastreo
        run: python sismos.py

      - name: Guardar historial
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add vistos.txt
          git commit -m "Update vistos.txt [skip ci]" || exit 0
          git push
