name: Monitor de Sismos Colombia

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check-earthquakes:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Otorga permisos directos para modificar el archivo
    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar librerías
        run: pip install requests

      - name: Ejecutar script de rastreo
        run: python sismos.py

      - name: Guardar historial de sismos notificados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add vistos.txt
          git commit -m "Actualizar vistos.txt" || exit 0
          git push
